export bold="\[$(tput bold)\]"
export underline="\[$(tput sgr 0 1)\]"
export rst="\[$(tput sgr0)\]"

export purple="\[$(tput setaf 171)\]"
export red="\[$(tput setaf 1)\]"
export grey="\[$(tput setaf 248)\]"
export green="\[$(tput setaf 34)\]"
export blue="\[$(tput setaf 38)\]"
export blueish="\[$(tput setaf 111)\]"
export yellow="\[$(tput setaf 178)\]"
export brownish="\[$(tput setaf 137)\]"
export black="\[$(tput setaf 0)\]"
export greybg="\[$(tput setab 248)\]"
export white="\[$(tput setaf 15)\]"

